// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/gomp/v1/job.proto

package v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MiningJob represents a work template for miners
type MiningJob struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JobId             string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	PrevHash          string                 `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	Coinb1            string                 `protobuf:"bytes,3,opt,name=coinb1,proto3" json:"coinb1,omitempty"`
	Coinb2            string                 `protobuf:"bytes,4,opt,name=coinb2,proto3" json:"coinb2,omitempty"`
	MerkleBranch      []string               `protobuf:"bytes,5,rep,name=merkle_branch,json=merkleBranch,proto3" json:"merkle_branch,omitempty"`
	Version           string                 `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	Nbits             string                 `protobuf:"bytes,7,opt,name=nbits,proto3" json:"nbits,omitempty"`
	Ntime             string                 `protobuf:"bytes,8,opt,name=ntime,proto3" json:"ntime,omitempty"`
	CleanJobs         bool                   `protobuf:"varint,9,opt,name=clean_jobs,json=cleanJobs,proto3" json:"clean_jobs,omitempty"`
	BlockHeight       int64                  `protobuf:"varint,10,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	NetworkDifficulty float64                `protobuf:"fixed64,11,opt,name=network_difficulty,json=networkDifficulty,proto3" json:"network_difficulty,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MiningJob) Reset() {
	*x = MiningJob{}
	mi := &file_proto_gomp_v1_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiningJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiningJob) ProtoMessage() {}

func (x *MiningJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomp_v1_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiningJob.ProtoReflect.Descriptor instead.
func (*MiningJob) Descriptor() ([]byte, []int) {
	return file_proto_gomp_v1_job_proto_rawDescGZIP(), []int{0}
}

func (x *MiningJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *MiningJob) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *MiningJob) GetCoinb1() string {
	if x != nil {
		return x.Coinb1
	}
	return ""
}

func (x *MiningJob) GetCoinb2() string {
	if x != nil {
		return x.Coinb2
	}
	return ""
}

func (x *MiningJob) GetMerkleBranch() []string {
	if x != nil {
		return x.MerkleBranch
	}
	return nil
}

func (x *MiningJob) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MiningJob) GetNbits() string {
	if x != nil {
		return x.Nbits
	}
	return ""
}

func (x *MiningJob) GetNtime() string {
	if x != nil {
		return x.Ntime
	}
	return ""
}

func (x *MiningJob) GetCleanJobs() bool {
	if x != nil {
		return x.CleanJobs
	}
	return false
}

func (x *MiningJob) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *MiningJob) GetNetworkDifficulty() float64 {
	if x != nil {
		return x.NetworkDifficulty
	}
	return 0
}

func (x *MiningJob) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MiningJob) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// JobTemplate is used internally by jobmanager
type JobTemplate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TemplateId        string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	PrevHash          string                 `protobuf:"bytes,2,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`
	CoinbaseTx        string                 `protobuf:"bytes,3,opt,name=coinbase_tx,json=coinbaseTx,proto3" json:"coinbase_tx,omitempty"`
	Transactions      []string               `protobuf:"bytes,4,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Version           string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Nbits             string                 `protobuf:"bytes,6,opt,name=nbits,proto3" json:"nbits,omitempty"`
	Ntime             string                 `protobuf:"bytes,7,opt,name=ntime,proto3" json:"ntime,omitempty"`
	BlockHeight       int64                  `protobuf:"varint,8,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	NetworkDifficulty float64                `protobuf:"fixed64,9,opt,name=network_difficulty,json=networkDifficulty,proto3" json:"network_difficulty,omitempty"`
	BlockReward       int64                  `protobuf:"varint,10,opt,name=block_reward,json=blockReward,proto3" json:"block_reward,omitempty"`
	TotalFees         int64                  `protobuf:"varint,11,opt,name=total_fees,json=totalFees,proto3" json:"total_fees,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JobTemplate) Reset() {
	*x = JobTemplate{}
	mi := &file_proto_gomp_v1_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobTemplate) ProtoMessage() {}

func (x *JobTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomp_v1_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobTemplate.ProtoReflect.Descriptor instead.
func (*JobTemplate) Descriptor() ([]byte, []int) {
	return file_proto_gomp_v1_job_proto_rawDescGZIP(), []int{1}
}

func (x *JobTemplate) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *JobTemplate) GetPrevHash() string {
	if x != nil {
		return x.PrevHash
	}
	return ""
}

func (x *JobTemplate) GetCoinbaseTx() string {
	if x != nil {
		return x.CoinbaseTx
	}
	return ""
}

func (x *JobTemplate) GetTransactions() []string {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *JobTemplate) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *JobTemplate) GetNbits() string {
	if x != nil {
		return x.Nbits
	}
	return ""
}

func (x *JobTemplate) GetNtime() string {
	if x != nil {
		return x.Ntime
	}
	return ""
}

func (x *JobTemplate) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *JobTemplate) GetNetworkDifficulty() float64 {
	if x != nil {
		return x.NetworkDifficulty
	}
	return 0
}

func (x *JobTemplate) GetBlockReward() int64 {
	if x != nil {
		return x.BlockReward
	}
	return 0
}

func (x *JobTemplate) GetTotalFees() int64 {
	if x != nil {
		return x.TotalFees
	}
	return 0
}

func (x *JobTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// NewBlockNotification is sent when a new block is found on the network
type NewBlockNotification struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BlockHash         string                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockHeight       int64                  `protobuf:"varint,2,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	NetworkDifficulty float64                `protobuf:"fixed64,3,opt,name=network_difficulty,json=networkDifficulty,proto3" json:"network_difficulty,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NewBlockNotification) Reset() {
	*x = NewBlockNotification{}
	mi := &file_proto_gomp_v1_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewBlockNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewBlockNotification) ProtoMessage() {}

func (x *NewBlockNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomp_v1_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewBlockNotification.ProtoReflect.Descriptor instead.
func (*NewBlockNotification) Descriptor() ([]byte, []int) {
	return file_proto_gomp_v1_job_proto_rawDescGZIP(), []int{2}
}

func (x *NewBlockNotification) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *NewBlockNotification) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *NewBlockNotification) GetNetworkDifficulty() float64 {
	if x != nil {
		return x.NetworkDifficulty
	}
	return 0
}

func (x *NewBlockNotification) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// DifficultyAdjustment is sent when network difficulty changes
type DifficultyAdjustment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldDifficulty float64                `protobuf:"fixed64,1,opt,name=old_difficulty,json=oldDifficulty,proto3" json:"old_difficulty,omitempty"`
	NewDifficulty float64                `protobuf:"fixed64,2,opt,name=new_difficulty,json=newDifficulty,proto3" json:"new_difficulty,omitempty"`
	BlockHeight   int64                  `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DifficultyAdjustment) Reset() {
	*x = DifficultyAdjustment{}
	mi := &file_proto_gomp_v1_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DifficultyAdjustment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DifficultyAdjustment) ProtoMessage() {}

func (x *DifficultyAdjustment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gomp_v1_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DifficultyAdjustment.ProtoReflect.Descriptor instead.
func (*DifficultyAdjustment) Descriptor() ([]byte, []int) {
	return file_proto_gomp_v1_job_proto_rawDescGZIP(), []int{3}
}

func (x *DifficultyAdjustment) GetOldDifficulty() float64 {
	if x != nil {
		return x.OldDifficulty
	}
	return 0
}

func (x *DifficultyAdjustment) GetNewDifficulty() float64 {
	if x != nil {
		return x.NewDifficulty
	}
	return 0
}

func (x *DifficultyAdjustment) GetBlockHeight() int64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

func (x *DifficultyAdjustment) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_gomp_v1_job_proto protoreflect.FileDescriptor

const file_proto_gomp_v1_job_proto_rawDesc = "" +
	"\n" +
	"\x17proto/gomp/v1/job.proto\x12\agomp.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x03\n" +
	"\tMiningJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tprev_hash\x18\x02 \x01(\tR\bprevHash\x12\x16\n" +
	"\x06coinb1\x18\x03 \x01(\tR\x06coinb1\x12\x16\n" +
	"\x06coinb2\x18\x04 \x01(\tR\x06coinb2\x12#\n" +
	"\rmerkle_branch\x18\x05 \x03(\tR\fmerkleBranch\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x12\x14\n" +
	"\x05nbits\x18\a \x01(\tR\x05nbits\x12\x14\n" +
	"\x05ntime\x18\b \x01(\tR\x05ntime\x12\x1d\n" +
	"\n" +
	"clean_jobs\x18\t \x01(\bR\tcleanJobs\x12!\n" +
	"\fblock_height\x18\n" +
	" \x01(\x03R\vblockHeight\x12-\n" +
	"\x12network_difficulty\x18\v \x01(\x01R\x11networkDifficulty\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xa5\x03\n" +
	"\vJobTemplate\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x12\x1b\n" +
	"\tprev_hash\x18\x02 \x01(\tR\bprevHash\x12\x1f\n" +
	"\vcoinbase_tx\x18\x03 \x01(\tR\n" +
	"coinbaseTx\x12\"\n" +
	"\ftransactions\x18\x04 \x03(\tR\ftransactions\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x14\n" +
	"\x05nbits\x18\x06 \x01(\tR\x05nbits\x12\x14\n" +
	"\x05ntime\x18\a \x01(\tR\x05ntime\x12!\n" +
	"\fblock_height\x18\b \x01(\x03R\vblockHeight\x12-\n" +
	"\x12network_difficulty\x18\t \x01(\x01R\x11networkDifficulty\x12!\n" +
	"\fblock_reward\x18\n" +
	" \x01(\x03R\vblockReward\x12\x1d\n" +
	"\n" +
	"total_fees\x18\v \x01(\x03R\ttotalFees\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc1\x01\n" +
	"\x14NewBlockNotification\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\tR\tblockHash\x12!\n" +
	"\fblock_height\x18\x02 \x01(\x03R\vblockHeight\x12-\n" +
	"\x12network_difficulty\x18\x03 \x01(\x01R\x11networkDifficulty\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xc1\x01\n" +
	"\x14DifficultyAdjustment\x12%\n" +
	"\x0eold_difficulty\x18\x01 \x01(\x01R\roldDifficulty\x12%\n" +
	"\x0enew_difficulty\x18\x02 \x01(\x01R\rnewDifficulty\x12!\n" +
	"\fblock_height\x18\x03 \x01(\x03R\vblockHeight\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB'Z%github.com/bardlex/gomp/proto/gomp/v1b\x06proto3"

var (
	file_proto_gomp_v1_job_proto_rawDescOnce sync.Once
	file_proto_gomp_v1_job_proto_rawDescData []byte
)

func file_proto_gomp_v1_job_proto_rawDescGZIP() []byte {
	file_proto_gomp_v1_job_proto_rawDescOnce.Do(func() {
		file_proto_gomp_v1_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gomp_v1_job_proto_rawDesc), len(file_proto_gomp_v1_job_proto_rawDesc)))
	})
	return file_proto_gomp_v1_job_proto_rawDescData
}

var file_proto_gomp_v1_job_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_gomp_v1_job_proto_goTypes = []any{
	(*MiningJob)(nil),             // 0: gomp.v1.MiningJob
	(*JobTemplate)(nil),           // 1: gomp.v1.JobTemplate
	(*NewBlockNotification)(nil),  // 2: gomp.v1.NewBlockNotification
	(*DifficultyAdjustment)(nil),  // 3: gomp.v1.DifficultyAdjustment
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_gomp_v1_job_proto_depIdxs = []int32{
	4, // 0: gomp.v1.MiningJob.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: gomp.v1.MiningJob.expires_at:type_name -> google.protobuf.Timestamp
	4, // 2: gomp.v1.JobTemplate.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: gomp.v1.NewBlockNotification.timestamp:type_name -> google.protobuf.Timestamp
	4, // 4: gomp.v1.DifficultyAdjustment.timestamp:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_gomp_v1_job_proto_init() }
func file_proto_gomp_v1_job_proto_init() {
	if File_proto_gomp_v1_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gomp_v1_job_proto_rawDesc), len(file_proto_gomp_v1_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_gomp_v1_job_proto_goTypes,
		DependencyIndexes: file_proto_gomp_v1_job_proto_depIdxs,
		MessageInfos:      file_proto_gomp_v1_job_proto_msgTypes,
	}.Build()
	File_proto_gomp_v1_job_proto = out.File
	file_proto_gomp_v1_job_proto_goTypes = nil
	file_proto_gomp_v1_job_proto_depIdxs = nil
}
